services:
  app:
    image: my-spring-app
    build: .
    ports:
      - "8080:8080"

#  db:
#    image: mysql:8.0
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: mydb
#    ports:
#      - "3306:3306"
